server:
  port: 9090
spring:
  security:
    filter:
      order: 10
  datasource:
    username: mailChatViewAppUser
    url: jdbc:mysql://localhost:3306/mailChatViewDb
    password: yx7oZA9QpomHBWnh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

jwt:
  access-token:
    validity: 18000
  refresh-token:
    validity: 1209600
