server:
  port: 9090
spring:
  security:
    filter:
      order: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

database:
  username: mailChatViewAppUser
  url: jdbc:mysql://mysqlServer:3306/mailChatViewDb
  driver-class-name: com.mysql.cj.jdbc.Driver

google:
  scope: https://www.googleapis.com/auth/gmail.readonly

jwt:
  access-token:
    validity: 18000
  refresh-token:
    validity: 1209600

mail-fetch:
  max-result: 20